# Generated by Django 4.1.3 on 2022-11-14 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now_add=True, verbose_name='date of stock')),
                ('product_name', models.CharField(max_length=100, verbose_name='product name')),
                ('net_weight', models.PositiveIntegerField(verbose_name='weight in tonnes')),
                ('qty', models.PositiveIntegerField(verbose_name='quantity')),
                ('isle', models.CharField(choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)], default=0, max_length=5, verbose_name='shelf no:')),
                ('tags', models.CharField(choices=[('cereals', 'cereals'), ('flour', 'flour'), ('dairy', 'dairy'), ('oil', 'oil')], max_length=50, verbose_name='select tag')),
                ('storage', models.CharField(choices=[('freezer', 'freezer'), ('dry', 'dry'), ('low', 'low'), ('canned', 'canned')], max_length=50, verbose_name='storage conditions')),
                ('shelf_life', models.DurationField(null=True)),
                ('exp', models.DateField(null=True, verbose_name='Expiry date')),
                ('status', models.CharField(max_length=25, null=True, verbose_name='comment')),
                ('attendant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='handler', to=settings.AUTH_USER_MODEL, verbose_name='handler')),
            ],
            options={
                'ordering': ['product_name', '-date'],
                'permissions': [('can_allow_dispatch', 'can allow dispatch'), ('can_make_reorders', 'can make new orders')],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_qty', models.PositiveIntegerField(verbose_name='quantity sold')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='attendant')),
                ('stock_sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shop.stock', verbose_name='Stock sold')),
            ],
            options={
                'ordering': ['-date'],
                'permissions': [('can_allow_dispatch', 'can allow dispatch')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.department')),
            ],
        ),
    ]
