# Generated by Django 4.0 on 2022-06-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now_add=True, verbose_name='date of stock')),
                ('product_name', models.CharField(max_length=100, verbose_name='product name')),
                ('net_weight', models.PositiveIntegerField(verbose_name='weight in tonnes')),
                ('qty', models.PositiveIntegerField(verbose_name='quantity')),
                ('isle', models.PositiveIntegerField(default=0, verbose_name='shelf no:')),
                ('tags', models.CharField(choices=[('non-edible', 'non-edible'), ('edible', 'edible'), ('cereals', 'cereals'), ('flour', 'flour'), ('fat_oils', 'fat_oils')], max_length=50, verbose_name='select tag')),
                ('storage', models.CharField(choices=[('freezer', 'freezer'), ('dry', 'dry'), ('low', 'low'), ('air_tight', 'air_tight')], max_length=50, verbose_name='storage conditions')),
                ('shelf_life', models.CharField(blank=True, max_length=50, verbose_name='shelf life')),
                ('status', models.CharField(max_length=25, null=True, verbose_name='status')),
                ('docs', models.FileField(null=True, upload_to='documents', verbose_name='documentation')),
                ('attendant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='handler', to='auth.user', verbose_name='handler')),
            ],
            options={
                'ordering': ['-product_name', 'date'],
                'permissions': [('can_allow_dispatch', 'can allow dispatch'), ('can_make_reorders', 'can make new orders')],
            },
        ),
    ]
