# Generated by Django 4.0 on 2022-07-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='exp',
            field=models.DateField(null=True, verbose_name='Expiry date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(max_length=25, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='storage',
            field=models.CharField(choices=[('freezer', 'freezer'), ('dry', 'dry'), ('low', 'low'), ('air_tight', 'air_tight'), ('canned', 'canned')], max_length=50, verbose_name='storage conditions'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tags',
            field=models.CharField(choices=[('cereals', 'cereals'), ('flour', 'flour'), ('fat_oils', 'fat_oils'), ('dairy', 'dairy')], max_length=50, verbose_name='select tag'),
        ),
    ]
