# Generated by Django 4.0 on 2022-09-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0002_stock_exp_alter_stock_status_alter_stock_storage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-product_name', '-date'], 'permissions': [('can_allow_dispatch', 'can allow dispatch'), ('can_make_reorders', 'can make new orders')]},
        ),
        migrations.AlterField(
            model_name='stock',
            name='docs',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='documentation'),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_qty', models.PositiveIntegerField(verbose_name='quantity sold')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='auth.user', verbose_name='attendant')),
                ('stock_sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shop.stock', verbose_name='Stock sold')),
            ],
            options={
                'ordering': ['-date'],
                'permissions': [('can_allow_dispatch', 'can allow dispatch')],
            },
        ),
    ]
