# Generated by Django 4.0 on 2022-09-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_deparment_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='deparment',
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['product_name', '-date'], 'permissions': [('can_allow_dispatch', 'can allow dispatch'), ('can_make_reorders', 'can make new orders')]},
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
